# Generated by Django 3.0.2 on 2020-01-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsOff',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('passw', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MuOff',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('passw', models.CharField(max_length=50)),
            ],
        ),
    ]
