# Generated by Django 3.0.2 on 2020-01-17 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('fund', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InsOff',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('passw', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MuOff',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('passw', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
                ('pin', models.IntegerField()),
                ('length', models.FloatField()),
                ('lane', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Construction')),
                ('municipal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.MuOff')),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_date', models.DateField()),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Construction')),
                ('municipal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.MuOff')),
            ],
        ),
        migrations.AddField(
            model_name='construction',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.InsOff'),
        ),
        migrations.AddField(
            model_name='construction',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Road'),
        ),
    ]
